services:
  node:
    image: node:18
    container_name: playwright_node
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - playwright-net
    working_dir: /usr/src/app
    stdin_open: true
    tty: true

networks:
  playwright-net:
    driver: bridge
